export const CONNECTION_TYPE = {
  ID: 'ID',
  REQUEST_ID: 'REQUEST_ID',
  DOMAIN_NAME: 'DOMAIN_NAME',
  ENTITY_NAME: 'ENTITY_NAME',
  INSERT_TIMESTAMP: 'INSERT_TIMESTAMP',
  MODIFIED_DATE: 'MODIFIED_DATE',
  IS_ACTIVE: 'IS_ACTIVE',
  APPROVED_BY_DPO: 'APPROVED_BY_DPO',
  UPDATED_BY: 'UPDATED_BY',
};