export const LEGAL_ENTITY_TYPE = {
  ID: 'ID',
  REQUEST_ID: 'REQUEST_ID',
  LEGAL_ENTITY_CODE: 'LEGAL_ENTITY_CODE',
  INSERT_TIMESTAMP: 'INSERT_TIMESTAMP',
  MODIFIED_DATE: 'MODIFIED_DATE',
  IS_ACTIVE: 'IS_ACTIVE',
  APPROVED_BY_DATA_OWNER: 'APPROVED_BY_DATA_OWNER',
  DATA_OWNER: 'DATA_OWNER',
  LEGAL_ENTITY_NAME: 'LEGAL_ENTITY_NAME',
};